trigger:
- release

pool:
  name: Default
  demands:
  - agent.name -equals dpcode

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Docker@2
      inputs:
        containerRegistry: 'Azure'
        repository: 'dpcode72/java-com'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'

- stage: Push
  jobs:
  - job: PushJob
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Azure'
        repository: 'dpcode72/java-com'
        command: 'push'
        tags: '$(Build.BuildId)'
        dockerRegistryEndpoint: 'dpcode.azurecr.io'
        dockerUsername: ''
        dockerPassword: '$(acrPassword)' 
